Channel: "5891096865:AAFHsDFzfFfgFDBDIUe5drg68OKsDOu9HUw"
ChatID: "-1001809111657"
Blaze: "https://blaze.com/api/roulette_games/history"
ChatGPT: "https://api.openai.com/v1/completions"
Token: "Bearer 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"
Model: "ada:ft-personal:double-ada-2023-02-10-20-28-45"
